### ISSUE TITLE
CSS @supports

### ISSUE THREAD

**Issue by clumsyme** [clumsyme/blogs#2]
## 语法：

```css
@supports <supports_condition> {
      /* specific rules */
}
```

在`supports_condition`为`true`时应用`specific rules`。

## 例

```css
.test {
    @support (--css-variables: 1) {
        --main-color: lime
    }
}
```

上例在浏览器支持`--css-variables: 1`这样的CSS样式格式时，`test`类会应用`--main-color: lime`这一条样式规则。
